name: CI/CD Pipeline to AWS
on:
  push:
    branches:
      - main
      # - develop
    # tags:
    #   - 'v*'
  pull_request:
    branches:
      - main
      # - develop
    paths-ignore:
      - 'README.md'
    
env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: dev-${{ github.run_number }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  repo_checkout:
    name: Checkout to github
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
  aws_login_build_push:
    needs: repo_checkout
    name: Builds and push to ecr
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        if: github.event_name != 'pull_request'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            --build-arg REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}\
            -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
            -t $REGISTRY/$IMAGE_NAME:latest \
            .
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG

     
