name: CI/CD Pipeline to AWS
on:
  push:
    branches:
      - main-dev
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
    
env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: dev-${{ github.run_number }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  aws_login_build_push:
    name: Checkout to github build and push to ecr
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Need write permission to commit and push changes
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        if: github.event_name != 'pull_request'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} \
            --build-arg REACT_APP_ENV=${{ secrets.REACT_APP_ENV }}\
            -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG \
            -t $REGISTRY/$IMAGE_NAME:latest \
            .
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG



      - name: Clone frontend_deployment repository
        uses: actions/checkout@v3
        with:
          repository: NineTalents-Agency/frontend_deployment
          token: ${{ secrets.CHECKOUT_TOKEN }}  
          path: deployment
          

      - name: Update ArgoCD deployment.yml
        env:
            # REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REGISTRY: 93796654438.dkr.ecr.us-east-1.amazonaws.com
        run: |
          sed -i "s|image: .*|image: $REGISTRY/$IMAGE_NAME:$IMAGE_TAG|g" deployment/deployment/deployment.yaml
      - name: Commit and push changes to ArgoCD repo
        run: |
          cd deployment
          git config --global user.name "chriscrsov"
          git config --global user.email "chriscrsov@gmail.com"
          git add deployment/deployment.yaml
          git commit -m "core: update deployment image to $IMAGE_TAG [skip ci]" || echo "No changes to commit"
          git push



















































  # deploy:
  #   name: Deploy to EKS
  #   runs-on: ubuntu-latest
  #   needs: aws_login_build_push
  #   if: github.event_name != 'pull_request'

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #       with:
  #         ref: main  # Pull latest changes including updated deployment file

  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1

  #     - name: Setup prerequisites (auto-installs everything)
  #       run: |
  #         cd automation_script
  #         sudo ./check_prerequisites.py

  #     - name: Deploy to EKS
  #       run: |
  #         cd automation_script
  #         ./deploy_frontend.py